Set up a basic block type
frees-au/ce pull request #39
Opened 2024-05-16 03:02 UTC by tannguyen04

## Description

closes #12

2024-05-16 03:15 UTC, tannguyen04 commented
Hi @simesy 
I have setup a basic block type with content field.
https://setup-basic-block-type-2lzuyga-fw7ucnhzydcsy.au.platformsh.site/ce

2024-05-16 04:01 UTC, simesy requested changes

2024-05-16 04:01 UTC, simesy commented on config/sync/core.entity_view_display.block_content.basic.default.yml
> +    label: above
Should not be a label?

2024-05-16 04:01 UTC, simesy commented on config/sync/field.field.block_content.basic.body.yml
> +field_name: body
In the node the field is called `markup` I would like to keep this consistent.

2024-05-16 04:04 UTC, simesy commented
@tannguyen04 can you also add a block in the footer with 

```
Free Sauce continues to acknowledge the Traditional Owners and Custodians of the lands on which we work. We pay our respects to Indigenous Elders past, present, and emerging. Sovereignty has never been ceded. It always was and always will be Aboriginal land.
```

I'll add other stuff later.

2024-05-17 00:50 UTC, tannguyen04 commented
> @tannguyen04 can you also add a block in the footer with
> 
> ```
> Free Sauce continues to acknowledge the Traditional Owners and Custodians of the lands on which we work. We pay our respects to Indigenous Elders past, present, and emerging. Sovereignty has never been ceded. It always was and always will be Aboriginal land.
> ```
> 
> I'll add other stuff later.

Added https://setup-basic-block-type-2lzuyga-fw7ucnhzydcsy.au.platformsh.site/ce

2024-05-17 01:08 UTC, simesy approved these changes

2024-05-17 08:31 UTC, merged